apiVersion: apps/v1
kind: Deployment
metadata:
  name: digivoterz-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: kaviya106/digivoterz-backend:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"
        env:
        - name: MONGO_URI
          value: "mongodb://mongo-service:27017/digivoterz"